name = "Jdl"
grammar = "jdl"
path_suffixes = ["jdl"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
tab_size = 2
hard_tabs = false

brackets = [
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
]
